import { Item } from './app/shared/models/Item';

export const sample_items: Item[] = [
  {
    id: '1',
    name: 'Taylor Swift',
    description: 'afasfasf',
    price: 10,
    favorite: false,
    origins: ['ts'],
    stars: 4.5,
    imageUrl: 'assets/taylor-swift.jpg',
    tags: ['ts', 'ts', 'ts'],
  },
  {
    id: '2',
    name: 'Taylor Swift',
    price: 20,
    description: 'fasfasf',
    favorite: true,
    origins: ['ts', 'ts', 'ts'],
    stars: 4.7,
    imageUrl: 'assets/taylor-swift.jpg',
    tags: ['ts', 'ts'],
  },
  {
    id: '3',
    name: 'Taylor Swift',
    price: 5,
    description: 'fasfasf',
    favorite: false,
    origins: ['ts', 'ts'],
    stars: 3.5,
    imageUrl: 'assets/taylor-swift.jpg',
    tags: ['ts', 'ts'],
  },
  {
    id: '4',
    name: 'Taylor Swift',
    price: 2,
    description: 'fasfasf',
    favorite: true,
    origins: ['ts', 'ts'],
    stars: 3.3,
    imageUrl: 'assets/taylor-swift.jpg',
    tags: ['ts', 'ts'],
  },
  {
    id: '5',
    name: 'Taylor Swift',
    price: 11,
    description: 'fasfasfasf',
    favorite: false,
    origins: ['ts', 'ts'],
    stars: 3.0,
    imageUrl: 'assets/taylor-swift.jpg',
    tags: ['ts', 'ts'],
  },
  {
    id: '6',
    name: 'Taylor Swift',
    price: 9,
    description: 'fasfasf',
    favorite: false,
    origins: ['ts'],
    stars: 4.0,
    imageUrl: 'assets/taylor-swift.jpg',
    tags: ['ts', 'ts', 'ts'],
  },
];
